"""add status_task and relationships

Revision ID: 0c5083a76ee6
Revises: cef193a84d8f
Create Date: 2023-04-21 22:21:15.315739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c5083a76ee6'
down_revision = 'cef193a84d8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_task',
    sa.Column('id_status', sa.Integer(), nullable=False),
    sa.Column('status_name', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id_status')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('id_user',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id_appr_type',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('id_status',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'status_task', ['id_status'], ['id_status'])
        batch_op.create_foreign_key(None, 'user', ['id_user'], ['id'])
        batch_op.create_foreign_key(None, 'approved_types', ['id_appr_type'], ['id_appr_type'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('id_status',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('id_appr_type',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('id_user',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('status_task')
    # ### end Alembic commands ###
