"""create new db

Revision ID: 1d8f87795ea0
Revises: cf89beae90f0
Create Date: 2023-03-16 22:28:39.504072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d8f87795ea0'
down_revision = 'cf89beae90f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approved_types', schema=None) as batch_op:
        batch_op.alter_column('number_record',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approved_types', schema=None) as batch_op:
        batch_op.alter_column('number_record',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
