"""add verification_data table

Revision ID: 215da489160e
Revises: 5dd2c03a704c
Create Date: 2023-04-19 00:10:09.832952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215da489160e'
down_revision = '5dd2c03a704c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_data',
    sa.Column('id_appr_type', sa.Integer(), nullable=False),
    sa.Column('model_si', sa.String(length=1024), nullable=False),
    sa.Column('ver_data', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id_appr_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verification_data')
    # ### end Alembic commands ###
