"""Tasks table

Revision ID: cef193a84d8f
Revises: 215da489160e
Create Date: 2023-04-20 00:53:21.808479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef193a84d8f'
down_revision = '215da489160e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id_task', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_appr_type', sa.Integer(), nullable=False),
    sa.Column('model_mi', sa.String(length=512), nullable=True),
    sa.Column('serial_number', sa.Integer(), nullable=True),
    sa.Column('protocol_number', sa.String(length=64), nullable=True),
    sa.Column('id_status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_task')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
