"""users and news tables

Revision ID: cf89beae90f0
Revises: 
Create Date: 2023-03-13 22:08:04.700130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf89beae90f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approved_types',
    sa.Column('id_appr_type', sa.Integer(), nullable=False),
    sa.Column('number_si', sa.String(length=10), nullable=False),
    sa.Column('name_si', sa.Text(), nullable=True),
    sa.Column('designation_si', sa.Text(), nullable=True),
    sa.Column('number_record', sa.Integer(), nullable=False),
    sa.Column('id_arshin', sa.Integer(), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('manufacturer_si', sa.String(), nullable=True),
    sa.Column('description_si', sa.String(), nullable=True),
    sa.Column('method_verif_si', sa.String(), nullable=True),
    sa.Column('proced_si', sa.String(), nullable=True),
    sa.Column('certificate_date', sa.Date(), nullable=True),
    sa.Column('mpi_si', sa.String(length=20), nullable=True),
    sa.Column('next_verif_si', sa.Boolean(), nullable=True),
    sa.Column('part_verif_si', sa.Boolean(), nullable=True),
    sa.Column('status_si', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_appr_type'),
    sa.UniqueConstraint('id_arshin'),
    sa.UniqueConstraint('number_record')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('approved_types')
    # ### end Alembic commands ###
